jwt:
  secret: ${SECRET_KEY:2f110de42cca5b47590a3c407abfa7fed1625e21153ac10ab7a860c40c8cd34e}
  access-token-expiration: ${ACC_EXP:900}
  refresh-token-expiration: ${REF_EXP:259200}

server:
  port: 8080
  servlet:
    context-path: /storage

spring:
  application:
    name: storage-box

  datasource:
    url: jdbc:mysql://interchange.proxy.rlwy.net:23299/railway?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PW:krXfJoQNRijrxHRxPlicrnzdTPvSYUQn}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
